%% (1+1)-ES FOR KNN HYPERPARAMETER ESTIMATION
% Code for the automatic computation of the hyperparameters required to
% train the KNN.
% It uses an evolutionary approach in which, at each iteration, a new
% candidate is generated by Gaussian mutation of the base-10 logarithm of
% the multiplicative factor applied to the base threshold.
% The fitness is computed using the function evaluate_KNNthreshold, which
% evaluates the threshold performance on a training dataset.
% The process continues until no significant improvement in fitness is
% observed for a given number of iterations or the maximum number of
% iterations is reached.
clear; close all; clc;

%% Fixed parameters and configuration
% File path for training
base_path = '20110929\';

% Spectrogram configuration parameters
window = 256;
overlap_ratio = (1 - 1/(2^3));
noverlap = floor(overlap_ratio * window);
nfft = window * 8;
f_min = 18;
f_max = 24;

% Initial threshold
base_threshold = 1e-15;

% Evolutionary algorithm configuration
max_iters = 50;
sigma = 0.1;
logf_min = -2;
logf_max = 3;

% Convergence configuration
patience = 8;
no_improve = 0;
min_delta = 5e-4;

%% Evolutionary process to optimize the threshold
% Range of k values (NumNeighbors) to test. KFold is internally fixed to 5.
N = 11806;
approx_k = round(sqrt(N));
k_vals = 1:approx_k;

% Initial value and evaluation
father_logf = 0;
father_threshold = base_threshold * 10^father_logf;

% Initial evaluation also returning the best k for this threshold
[father_fitness, father_k] = evaluate_KNNthreshold( ...
    father_threshold, base_path, window, noverlap, nfft, f_min, f_max, k_vals);

best_fitness = father_fitness;

% Arrays to store k and kfold of the best parent at each iteration
history_father_k = nan(max_iters,1);
history_iters = zeros(max_iters,1);
history_logf = zeros(max_iters,1);
history_fitness = zeros(max_iters,1);

% Arrays to store parent (father) evolution
history_father_logf = zeros(max_iters,1);
history_father_fitness = zeros(max_iters,1);
cont_total = 1;

% Initial message (includes k and folds)
fprintf('Start: factor=%.3f, threshold=%.3e, k=%g, fitness=%.4f\n', ...
    10^father_logf, father_threshold, father_k, father_fitness);

% Main loop
for iter = 1:max_iters
    % Mutation in log10 of the factor
    child_logf = father_logf + sigma * randn();

    % Limit to a reasonable range
    child_logf = min(max(child_logf, logf_min), logf_max);
    child_threshold = base_threshold * 10^child_logf;

    % Evaluate child (also returns the best k for this threshold)
    [child_fitness, child_k] = evaluate_KNNthreshold( ...
        child_threshold, base_path, window, noverlap, nfft, f_min, f_max, k_vals);

    % Store history
    history_iters(iter) = iter;
    history_logf(iter) = child_logf;
    history_fitness(iter) = child_fitness;

    % (1+1) selection based on achieved improvement.
    % If there is no significant improvement, it is counted toward convergence.
    % If the improvement is significant, the parent is updated and the counter reset.
    improvement = child_fitness - father_fitness;
    if improvement > min_delta * abs(father_fitness)
        father_logf = child_logf;
        father_threshold = child_threshold;
        father_fitness = child_fitness;
        % Update k/folds associated with the parent
        father_k = child_k;
        improved = true;
        no_improve = 0;
    else
        improved = false;
        no_improve = no_improve + 1;
    end

    % Save parent history at this iteration
    history_father_k(iter) = father_k;
    history_father_logf(iter) = father_logf;
    history_father_fitness(iter) = father_fitness;

    % Console log
    msg_marker = tern(improved, ' <--- new best (adopted)', '');
    fprintf('Iter %03d | threshold=%.3e | child_k=%d | fitness=%.4f %s\n', ...
        iter, child_threshold, child_k, child_fitness, msg_marker);

    % Check convergence criterion to stop the process
    if no_improve >= patience
        fprintf('\nConvergence reached: %d iterations without significant improvement.\n', ...
            no_improve);
        break;
    end

    % Iteration counter
    if iter ~= max_iters
        cont_total = cont_total + 1;
    end
end

% Final result
fprintf('\nFINAL RESULT: threshold=%.3e | best_k=%d | fitness=%.4f\n', ...
    father_threshold, father_k, father_fitness);

% Recalculate the number of stored iterations and prepare X axis
cont_total = find(history_iters ~= 0, 1, 'last');
if isempty(cont_total)
    cont_total = 0;
end

% Plot fitness evolution, parent fitness, and log10(factor)
figure;
x = 1:cont_total;

subplot(3,1,[1 2])
hold on
plot(x, history_fitness(1:cont_total), '-o', ...
    'Color', [0.047 0.039 0.243], 'LineWidth', 1);
plot(x, history_father_fitness(1:cont_total), '-pentagram', ...
    'Color', [0.702 0.247 0.384], 'LineWidth', 1);
xlabel('Iteration'); ylabel('Fitness'); grid on;
xlim([0 cont_total])
title('Fitness evolution');
legend("Fitness (general)", "Fitness (parent)", 'Location', 'southwest')
hold off

subplot(3,1,3);
plot(x, history_logf(1:cont_total), '-diamond', ...
    'Color', [0.976 0.337 0.31], 'LineWidth', 1);
xlabel('Iteration'); ylabel('log10(factor)'); grid on;
xlim([0 cont_total])
title('Evolution of the log10 factor');

% Inline ternary function for console messages
function s = tern(cond, a, b)
    if cond
        s = a;
    else
        s = b;
    end
end
