%% (1+1)-ES FOR SVM HYPERPARAMETER OPTIMIZATION
% Code for the automatic computation of the hyperparameters required to
% train the SVM.
% It uses an evolutionary approach in which, at each iteration, a new
% candidate is generated by Gaussian mutation of the base-10 logarithm of
% the multiplicative factor applied to the base threshold.
% The fitness is computed using the function evaluate_SVMthreshold, which
% evaluates the performance of the threshold on a training dataset.
% The process continues until no significant improvement in fitness is
% observed for a given number of iterations or the maximum number of
% iterations is reached.
clear; close all; clc;

%% Fixed parameters and configuration
% File path for training data
base_path = '20110929\';

% Spectrogram configuration parameters
window = 256;
overlap_ratio = (1 - 1/(2^3));
noverlap = floor(overlap_ratio * window);
nfft = window * 8;
f_min = 18;
f_max = 24;

% Initial threshold
base_threshold = 1e-15;

% Range of values for KernelFunction to test
functions = ["rbf","linear","polynomial"];

% Range of values for C (BoxConstraint) and KS (KernelScale)
C_vals = logspace(-2,2,5);
KS_vals = logspace(-1,1,5);

% Evolutionary strategy configuration
max_iters = 50;
sigma = 0.1;
logf_min = -2;
logf_max = 3;

% Convergence configuration
patience = 8;
no_improve = 0;
min_delta = 5e-4;

%% Evolutionary process to optimize the threshold
% Initial value and evaluation
father_logf = 0;
father_umbral = base_threshold * 10^father_logf;

% Initial evaluation, also obtaining the best SVM parameters for this threshold
[father_fitness, father_params] = evaluate_SVMthreshold( ...
    father_umbral, base_path, window, noverlap, nfft, ...
    f_min, f_max, functions, C_vals, KS_vals);

best_fitness = father_fitness;

% Arrays to store child fitness history
history_iters = zeros(max_iters,1);
history_logf = zeros(max_iters,1);
history_fitness = zeros(max_iters,1);

% Arrays to store the evolution of the parent (father)
history_father_logf = zeros(max_iters,1);
history_father_fitness = zeros(max_iters,1);
cont_total = 1;

% Initial message (includes kernel and hyperparameters)
fprintf('Start: threshold=%.3e | kernel=%s | C=%.3g | KS=%.3g | fitness=%.4f\n', ...
    father_umbral, father_params.Kernel, ...
    father_params.C, father_params.KernelScale, father_fitness);

% Main loop
for iter = 1:max_iters
    % Mutation in log10 of the factor
    child_logf = father_logf + sigma * randn();

    % Limit to a reasonable range
    child_logf = min(max(child_logf, logf_min), logf_max);
    child_umbral = base_threshold * 10^child_logf;

    % Evaluate child (also obtain best SVM parameters)
    [child_fitness, child_params] = evaluate_SVMthreshold( ...
        child_umbral, base_path, window, noverlap, nfft, ...
        f_min, f_max, functions, C_vals, KS_vals);

    % Store history
    history_iters(iter) = iter;
    history_logf(iter) = child_logf;
    history_fitness(iter) = child_fitness;

    % (1+1) selection based on fitness improvement
    improvement = child_fitness - father_fitness;
    if improvement > min_delta * abs(father_fitness)
        father_logf = child_logf;
        father_umbral = child_umbral;
        father_fitness = child_fitness;
        father_params = child_params;
        improved = true;
        no_improve = 0;
    else
        improved = false;
        no_improve = no_improve + 1;
    end

    % Store parent history at this iteration
    history_father_logf(iter) = father_logf;
    history_father_fitness(iter) = father_fitness;

    % Console log
    msg_marker = tern(improved, ' <--- new best (adopted)', '');
    fprintf(['Iter %03d | threshold=%.3e | kernel=%s | C=%.3g | KS=%.3g ', ...
             '| fitness=%.4f%s\n'], ...
        iter, child_umbral, child_params.Kernel, ...
        child_params.C, child_params.KernelScale, ...
        child_fitness, msg_marker);

    % Check convergence criterion
    if no_improve >= patience
        fprintf('\nConvergence reached: %d iterations without significant improvement.\n', no_improve);
        break;
    end

    % Iteration counter
    if iter ~= max_iters
        cont_total = cont_total + 1;
    end
end

%% Final result
fprintf('\nFINAL RESULT: threshold=%.3e | kernel=%s | C=%.3g | KS=%.3g | fitness=%.4f\n', ...
    father_umbral, father_params.Kernel, ...
    father_params.C, father_params.KernelScale, father_fitness);

% Recompute number of stored iterations and prepare X-axis
cont_total = find(history_iters ~= 0, 1, 'last');
if isempty(cont_total)
    cont_total = 0;
end

%% Plot fitness evolution, parent fitness, and log10 factor
figure;
x = 1:cont_total;

subplot(3,1,[1 2])
hold on
plot(x, history_fitness(1:cont_total), '-o', 'Color', [0.047 0.039 0.243], 'LineWidth', 1);
plot(x, history_father_fitness(1:cont_total), '-pentagram', 'Color', [0.702 0.247 0.384], 'LineWidth', 1);
xlabel('Iteration'); ylabel('Fitness'); grid on;
xlim([0 cont_total])
title('Fitness evolution');
legend("Fitness (child)", "Fitness (parent)", 'Location','southwest')
hold off

subplot(3,1,3);
plot(x, history_logf(1:cont_total), '-diamond', 'Color', [0.976 0.337 0.31], 'LineWidth', 1);
xlabel('Iteration'); ylabel('log10(factor)'); grid on;
xlim([0 cont_total])
title('Evolution of the log10 factor');

%% Inline ternary helper function for console messages
function s = tern(cond, a, b)
    if cond
        s = a;
    else
        s = b;
    end
end
